import React, { useState } from 'react';
import PropTypes from 'prop-types';

/**
 * @description Lists every file the current draft would change or add, each with its
 * full generated text ready to copy into GitHub's web UI. Nothing here ever touches
 * the filesystem — this is text output only.
 *
 * @param {Object} param
 * @param {Array} param.files - [{ path, content, note }]
 */
const OutputPanel = ({ files }) => {
  const [copiedPath, setCopiedPath] = useState(null);

  const handleCopy = async (path, content) => {
    try {
      await navigator.clipboard.writeText(content);
      setCopiedPath(path);
      window.setTimeout(() => setCopiedPath(null), 1500);
    } catch (error) {
      // Clipboard API may be unavailable; the text is still selectable in the block.
    }
  };

  if (files.length === 0) {
    return (
      <div className="adminOutputPanel adminOutputPanel-empty">
        <p>No changes yet. Edits you make will show up here as full file contents, ready to paste into GitHub.</p>
      </div>
    );
  }

  return (
    <div className="adminOutputPanel">
      <p className="adminOutputPanel-instructions">
        Apply these in order: for each file below, open it in the GitHub web UI (or create it, for new files),
        replace its full contents with the text shown, and commit. Files touching tests are noted with what to
        do locally afterward, since snapshots can only be generated by running Jest.
      </p>
      {files.map(({ path, content, note }) => (
        <section key={path} className="adminOutputPanel-file">
          <header>
            <code>{path}</code>
            <button type="button" onClick={() => handleCopy(path, content)}>
              {copiedPath === path ? 'Copied!' : 'Copy'}
            </button>
          </header>
          {note && <p className="adminOutputPanel-note">{note}</p>}
          <pre><code>{content}</code></pre>
        </section>
      ))}
    </div>
  );
};

OutputPanel.propTypes = {
  files: PropTypes.arrayOf(PropTypes.shape({
    path: PropTypes.string.isRequired,
    content: PropTypes.string.isRequired,
    note: PropTypes.string
  })).isRequired
};

export default OutputPanel;
