import React, { useState } from 'react';
import PropTypes from 'prop-types';

/**
 * @description Lists every file the current draft would change or add, each with its
 * full generated text ready to copy into GitHub's web UI. Nothing here ever touches
 * the filesystem — this is text output only.
 *
 * @param {Object} param
 * @param {Array} param.files - [{ path, content, note, deleted?, problems? }]
 */
const OutputPanel = ({ files }) => {
  // { path, ok } for the last Copy clicked — shown on that file's button.
  const [copyResult, setCopyResult] = useState(null);

  const handleCopy = async (path, content) => {
    try {
      await navigator.clipboard.writeText(content);
      setCopyResult({ path, ok: true });
      window.setTimeout(() => setCopyResult((current) => (current && current.path === path && current.ok ? null : current)), 1500);
    } catch (error) {
      // Clipboard access can be refused (no permission, an insecure page, an older
      // browser). Say so, rather than leaving the admin to paste stale clipboard text.
      setCopyResult({ path, ok: false });
    }
  };

  const copyLabel = (path) => {
    if (!copyResult || copyResult.path !== path) return 'Copy';
    return copyResult.ok ? 'Copied!' : 'Copy failed';
  };

  if (files.length === 0) {
    return (
      <div className="adminOutputPanel adminOutputPanel-empty">
        <p>No changes yet. Edits you make will show up here as full file contents, ready to paste into GitHub.</p>
      </div>
    );
  }

  const filesWithProblems = files.filter((file) => file.problems && file.problems.length > 0);
  const problemCount = filesWithProblems.reduce((total, file) => total + file.problems.length, 0);

  return (
    <div className="adminOutputPanel">
      {problemCount > 0 && (
        <div className="adminOutputPanel-problemSummary" role="alert">
          <strong>
            {problemCount === 1 ? '1 problem' : `${problemCount} problems`} to fix before applying these changes
          </strong>{' '}
          — each would show up wrong on the live site. Details are listed with{' '}
          {filesWithProblems.map((file) => file.path).join(', ')} below.
        </div>
      )}
      <p className="adminOutputPanel-instructions">
        Apply these in order: for each file below, open it in the GitHub web UI (or create it, for new files),
        replace its full contents with the text shown, and commit. Files touching tests are noted with what to
        do locally afterward, since snapshots can only be generated by running Jest.
      </p>
      {files.map(({ path, content, note, deleted, problems }) => (
        deleted ? (
          <div key={path} className="adminOutputPanel-file adminOutputPanel-file--deleted">
            <div className="adminOutputPanel-fileHeader">
              <span className="adminOutputPanel-deleteLabel">Delete this file</span>
              <code>{path}</code>
            </div>
            {note && <p className="adminOutputPanel-note">{note}</p>}
          </div>
        ) : (
          <div key={path} className="adminOutputPanel-file">
            <div className="adminOutputPanel-fileHeader">
              <code>{path}</code>
              <button type="button" onClick={() => handleCopy(path, content)}>{copyLabel(path)}</button>
            </div>
            {copyResult && copyResult.path === path && !copyResult.ok && (
              <p className="adminOutputPanel-copyError" role="alert">
                Couldn&apos;t copy to the clipboard — this browser didn&apos;t allow it. Select the text below and copy
                it by hand instead.
              </p>
            )}
            {problems && problems.length > 0 && (
              <ul className="adminOutputPanel-problems">
                {problems.map(({ where, problem }) => (
                  <li key={`${where} ${problem}`}><strong>{where}</strong> {problem}</li>
                ))}
              </ul>
            )}
            {note && <p className="adminOutputPanel-note">{note}</p>}
            <pre><code>{content}</code></pre>
          </div>
        )
      ))}
    </div>
  );
};

OutputPanel.propTypes = {
  files: PropTypes.arrayOf(PropTypes.shape({
    path: PropTypes.string.isRequired,
    content: PropTypes.string,
    note: PropTypes.string,
    // A file to delete in GitHub rather than write: shown with its path and note only.
    deleted: PropTypes.bool,
    // Things in this file that would show up wrong on the live site (draftProblems.js).
    problems: PropTypes.arrayOf(PropTypes.shape({ where: PropTypes.string, problem: PropTypes.string }))
  })).isRequired
};

export default OutputPanel;
